name: Release

on:
  push:
    branches:
      - master
      - beta

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check for Pre.json
        id: check-pre
        run: |
          if [[ "${{ github.ref_name }}" == "beta" ]]; then
            # For beta branch: Check if not in pre mode and report an error
            if [ -f ".changeset/pre.json" ]; then
              mode=$(jq -r '.mode' .changeset/pre.json)
              if [[ "$mode" != "pre" ]]; then
                echo "Error: Not in pre mode on beta branch. Exiting."
                exit 1
              else
                echo "In pre mode on beta branch. Proceeding."
              fi
            else
              echo "Error: pre.json not found. Exiting."
              exit 1
            fi


      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: |
            npx changeset pre exit || echo "pre exit failed, but continuing."
            npx changeset version
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
